# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GH_TOKEN: $(gh-token)
  python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest --alluredir=allure-results
  displayName: 'Run tests'

- script: | 
    git config --global user.name "A-S-A-S" 
    git config --global user.email "arseniy.smirnov@quantori.com" 
    git remote set-url origin https://$(gh-token)@github.com/A-S-A-S/restful-booking-for-azure.git 
    git clone https://$(gh-token)@github.com/A-S-A-S/restful-booking-for-azure.git 
    cd restful-booking-for-azure 
    git checkout -B gh-pages 
    cp -R ../allure-results/* . 
    cp -R ../gh-pages/history/* .    # Get Allure history 
    git add . 
    git commit -m "Update Allure report" 
    git push -f origin gh-pages 
  env: 
    GH_TOKEN: $(gh-token) 
  displayName: 'Push Allure reports to gh-pages' 