# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest --alluredir=allure-results
  displayName: 'Run tests with Allure'

- script: |
    git config --global user.name "anna-khvorostyanova"
    git config --global user.email "anna.khvorostyanova@quantori.com"
    git remote set-url origin https://$(gh-token)@github.com/anna-khvorostyanova/python-qa-restful-booking.git
    git clone https://$(gh-token)@github.com/anna-khvorostyanova/python-qa-restful-booking.git
    cd python-qa-restful-booking
    git checkout -B gh-pages
    cp -R ../allure-results/* .
    cp -R ../gh-pages/history/* .    # Get Allure history
    git add .
    git commit -m "Update Allure report"
    git push -f origin gh-pages
  env:
    GH_TOKEN: $(gh-token)
  displayName: 'Push Allure reports to gh-pages'
