trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  GH_TOKEN: $(gh-token)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
    displayName: 'Use Python 3.8'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      wget https://github.com/allure-framework/allure2/releases/download/2.22.1/allure-2.22.1.tgz
      tar -zxvf allure-2.22.1.tgz
      allure-2.22.1/bin/allure --version
    displayName: 'Install and Verify Allure'

  - script: |
      pytest --alluredir=allure-results
    displayName: 'Run tests'
    continueOnError: true

  - script: |
      allure-2.22.1/bin/allure generate allure-results -o allure-report --clean
    displayName: 'Generate Allure report'

  - script: |
      git config --global user.name "A-S-A-S" 
      git config --global user.email "arseniy.smirnov@quantori.com" 
      git remote set-url origin https://$(gh-token)@github.com/A-S-A-S/restful-booking-for-azure.git 
      git clone https://$(gh-token)@github.com/A-S-A-S/restful-booking-for-azure.git 
      cd restful-booking-for-azure 
      git checkout -B gh-pages 
      mkdir -p allure-report
      cp -R ../allure-results/* allure-report/
      cp -R ../gh-pages/history/* allure-report/
      git add . 
      git commit -m "Update Allure report" 
      git push -f origin gh-pages 
    env: 
      GH_TOKEN: $(gh-token) 
    displayName: 'Push Allure reports to gh-pages'
