trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  GH_TOKEN: $(gh-token)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
    displayName: 'Use Python 3.8'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      sudo apt-add-repository ppa:qameta/allure
      sudo apt-get update
      sudo apt-get install allure
    displayName: 'Install Allure Framework'

  - script: |
      allure --version
    displayName: 'Verify Allure installation'

  - script: |
      pytest --alluredir=$(Build.ArtifactStagingDirectory)/allure-results
    displayName: 'Run tests'

  - script: |
      allure generate $(Build.ArtifactStagingDirectory)/allure-results -o $(Build.ArtifactStagingDirectory)/allure-report --clean
    displayName: 'Generate Allure Report'

  - script: |
      git config --global user.name "A-S-A-S" 
      git config --global user.email "arseniy.smirnov@quantori.com" 
      git clone --depth 1 --branch gh-pages https://$(gh-token)@github.com/A-S-A-S/restful-booking-for-azure.git gh-pages
      cp -R $(Build.ArtifactStagingDirectory)/allure-report/* gh-pages/
    displayName: 'Clone gh-pages branch and Copy Allure Report'

  - script: |
      cd gh-pages
      git add .
      git commit -m "Update Allure report"
      git push origin gh-pages
    displayName: 'Commit and Push Allure Report to gh-pages'
